Feature authentication
xx3u/amal_backend pull request #108
Opened 2021-08-06 11:11 UTC by BauyrjanSeidahmet

# 101
Добавлена аутентифация пользователя
Дата: 06.08.2021
Время: 5 часов

2021-08-07 18:14 UTC, nurlan212 commented on src/controllers/UserController.js
> +        return res.status(500).send('User with this username already exists');
```suggestion
        return res.status(400).send({error: 'User with this username already exists'});
```

2021-08-07 18:20 UTC, nurlan212 commented on src/controllers/UserController.js
> +        return res.status(500).send('User with this username already exists');
надо отправить 400 статус, статус 500 не потходить, так как статусы 500-599 - казывают на серверные ошибки.

2021-08-07 19:19 UTC, nurlan212 reviewed
![image](https://user-images.githubusercontent.com/76464163/128611187-6d5972c5-acfd-4d1c-8ac7-2a5a5cae17ca.png)

Ошибка при запуска seed-ов (sequelize db:seed:all);

![image](https://user-images.githubusercontent.com/76464163/128611501-f1e667f0-4cde-4eec-9652-f479d977824b.png)

создание пользователя не работает;

Логин (авторизация) не смог проверить, так как регистрация не работает и в seed ошибка при созданые моковых данных для users

2021-08-07 19:19 UTC, nurlan212 commented on src/controllers/UserController.js
> +      res.status(400).send(error);
```suggestion
      res.status(500).send(error);
```
catch срабатывает при ошибке в серверной стороне, поэтому нужно отправить 500-ю ошубку.

2021-08-07 19:19 UTC, nurlan212 commented on src/controllers/UserController.js
> +        return res.status(500).send('Email or password does not match');
```suggestion
        return res.status(400).send({error: 'Email or password does not match'});
```

2021-08-07 19:19 UTC, nurlan212 commented on src/controllers/UserController.js
> +      await newUser.save();
```suggestion
      const newUser = await new User({ username, password: hashedPassword });
      await newUser.save();
```
надо держаться одной стили. Посмотри другие контроллеры (например создание/получение/редактирование записи)

2021-08-07 19:19 UTC, nurlan212 commented on src/controllers/UserController.js
> +        return res.status(500).send('Email or password does not match');
```suggestion
        return res.status(400).send({error: 'Email or password does not match'});
```

2021-08-07 19:19 UTC, nurlan212 commented on docker-compose.yml
> +      - JWT_KEY=secret
```suggestion
      - JWT_KEY=dTH#v1%^K!
```
Думаю, пароль надо установить чуть по сложнее, например, как это.

2021-08-07 19:19 UTC, nurlan212 commented on src/controllers/UserController.js
> +      res.status(400).send(error);
```suggestion
      res.status(500).send(error);
```

2021-08-08 10:36 UTC, BauyrjanSeidahmet commented on src/controllers/UserController.js
> +        return res.status(500).send('User with this username already exists');
исправлено

2021-08-08 10:39 UTC, BauyrjanSeidahmet commented on src/controllers/UserController.js
> +      res.status(400).send(error);
Исправлено. Сидер было заполнено данными.

2021-08-08 10:39 UTC, BauyrjanSeidahmet commented on src/controllers/UserController.js
> +        return res.status(500).send('Email or password does not match');
исправлено

2021-08-08 10:39 UTC, BauyrjanSeidahmet commented on src/controllers/UserController.js
> +      await newUser.save();
исправлено

2021-08-08 10:39 UTC, BauyrjanSeidahmet commented on src/controllers/UserController.js
> +        return res.status(500).send('Email or password does not match');
исправлено

2021-08-08 10:39 UTC, BauyrjanSeidahmet commented on docker-compose.yml
> +      - JWT_KEY=secret
исправлено

2021-08-08 10:39 UTC, BauyrjanSeidahmet commented on src/controllers/UserController.js
> +      res.status(400).send(error);
исправлено

2021-08-08 11:07 UTC, nurlan212 approved these changes

2021-08-08 14:13 UTC, OmegonAlpharius requested changes
Напиши  в тикете как проверять данный функционал

2021-08-08 14:13 UTC, OmegonAlpharius commented on src/routes/StudentRoutes.js
> +);
Почему только здесь аутентификация ?

2021-08-08 14:13 UTC, OmegonAlpharius commented on src/routes/UserRoutes.js
> +module.exports = router;
Добавь сразу валидацию json, используя Joi, смотри по аналогии студентов или lessons

2021-08-08 14:13 UTC, OmegonAlpharius commented on src/controllers/UserController.js
> +      const hashedPassword = await getHashedPassword(password);
Перенеси хеширование в модель https://sequelize.org/master/manual/getters-setters-virtuals.html
```suggestion
      const hashedPassword = await getHashedPassword(password);
```

2021-08-08 14:13 UTC, OmegonAlpharius commented on src/controllers/UserController.js
> +      if (!vaildPassword) {
Ошибка, и если переменная bool то можно добавить приставку  is 
```suggestion
      const isValidPassword = await bcrypt.compare(password, userWithUsername.password);
      if (!isValidPassword) {
```

2021-08-08 14:13 UTC, OmegonAlpharius commented on src/database/migrations/20210804090421-modify_users_add_new_fields.js
> +};
Нужно обернуть все в транзакцию https://sequelize.org/master/manual/migrations.html

2021-08-08 14:13 UTC, OmegonAlpharius commented on src/controllers/UserController.js
> +        return res.status(400).send({ error: 'Email or password does not match' });
Email   или username ? Приведи к одному названию

2021-08-08 14:13 UTC, OmegonAlpharius commented on src/controllers/UserController.js
> +      const userWithUsername = await User.findOne({ where: { username } });
Почему у переменной такое название ? Почему не user
```suggestion
      const userWithUsername = await User.findOne({ where: { username } });
```

2021-08-11 16:21 UTC, BauyrjanSeidahmet commented on src/routes/StudentRoutes.js
> +);
Написал в тикет как проверять данный функционал. Добавил ограничение и других роутах.

2021-08-11 16:21 UTC, BauyrjanSeidahmet commented on src/routes/UserRoutes.js
> +module.exports = router;
Добавил валидацию

2021-08-11 16:21 UTC, BauyrjanSeidahmet commented on src/controllers/UserController.js
> +      const hashedPassword = await getHashedPassword(password);
Перенес

2021-08-11 16:22 UTC, BauyrjanSeidahmet commented on src/controllers/UserController.js
> +      if (!vaildPassword) {
изменил название переменной

2021-08-11 16:22 UTC, BauyrjanSeidahmet commented on src/database/migrations/20210804090421-modify_users_add_new_fields.js
> +};
обернул в транзакцию

2021-08-11 16:22 UTC, BauyrjanSeidahmet commented on src/controllers/UserController.js
> +        return res.status(400).send({ error: 'Email or password does not match' });
Исправлено

2021-08-11 16:28 UTC, BauyrjanSeidahmet commented on src/controllers/UserController.js
> +      const userWithUsername = await User.findOne({ where: { username } });
Потому что, это переменная, для того чтобы проверить, есть ли такой юзернейм в системе. Чтобы не было дублирование.

2021-08-20 11:49 UTC, OmegonAlpharius approved these changes

2021-08-21 10:34 UTC, xx3u commented on src/models/user.js
> +        allowNull: false,
в модель не нужно добавлять unique: true?

2021-08-21 10:34 UTC, xx3u commented on src/controllers/UserController.js
> +  },
а функцию logout мы только на фронте делаем?

2021-08-21 10:45 UTC, BauyrjanSeidahmet commented on src/models/user.js
> +        allowNull: false,
Эту проверку написал к контроллере

2021-08-21 10:46 UTC, BauyrjanSeidahmet commented on src/controllers/UserController.js
> +  },
да

2021-08-21 12:06 UTC, BauyrjanSeidahmet commented on src/models/user.js
> +        allowNull: false,
unique: true добавил в модель и в миграцию, проверку в контроллер убрал.

2021-08-21 15:30 UTC, OmegonAlpharius commented on src/models/user.js
> +        allowNull: false,
Лучше проверку оставить, так понятное сообщение будет формироваться пользователю и статус ответа

2021-08-21 15:33 UTC, BauyrjanSeidahmet commented on src/models/user.js
> +        allowNull: false,
Проверил на фронте, текст ошибки нормально показывает

2021-08-22 11:53 UTC, merged