Изменен allowNull: false
xx3u/amal_backend pull request #41
Opened 2021-07-14 18:44 UTC by xx3u

При добавлении направления, необходимо изменить allowNull: false для name для того, чтобы имя направления не было пустым

2021-07-16 04:47 UTC, BauyrjanSeidahmet requested changes

2021-07-16 04:47 UTC, BauyrjanSeidahmet commented on src/database/migrations/20210708040243-create-stream.js
>        createdAt: {
После этого изменения, на фронте при нажатии кнопку "добавить студента" приложение падает 
![rev162](https://user-images.githubusercontent.com/86306282/125892499-dd0b2912-4a20-4412-a97f-bbb44ee90fe8.png)

Нужно сначала на фронте изменить код, в контейнере StudentsContainer, в переменной changedStudents, 
в значении ключа streamName писать student.Stream && student.Stream.name вместо просто student.Stream.name, таким образом,
![rev161](https://user-images.githubusercontent.com/86306282/125893202-fa1a1d46-9efb-4b2a-a9a9-8b8aeba822c2.png)

2021-07-17 06:56 UTC, xx3u commented on src/database/migrations/20210708040243-create-stream.js
>        createdAt: {
Ок, исправлено на фронте в тикете https://github.com/xx3u/amal_frontend/pull/92

2021-07-20 13:53 UTC, ZaurQoban approved these changes

2021-07-21 17:45 UTC, BauyrjanSeidahmet approved these changes

2021-07-21 17:47 UTC, merged