Create entity teacher
xx3u/amal_backend pull request #74
Opened 2021-07-25 07:12 UTC by nurlan212

#60 

Создана сущность Teacher. Добавлены контроллеры, роуты для CRUD операции.

Затрачено 4 часа

2021-07-25 11:10 UTC, OmegonAlpharius reviewed
Нужно добавить тестовых записей со связями,
И привести реализацию к единому стилю с проектом

2021-07-25 11:10 UTC, OmegonAlpharius commented on src/database/seeders/20210724164340-mock-data-teachers.js
> +};
Нужно добавить записей связанных с user, что-бы можно было тестить

2021-07-25 11:10 UTC, OmegonAlpharius commented on src/controllers/TeacherController.js
> +  },
Методы нужно в едином стиле писать, посмотри в других controllers
```suggestion
  async updateById(req, res) {
    try {
      const updatedTeacher = await Teacher.update(req.body, {
        where: {
          id: req.params.id,
        },
      });
      return res.status(200).send('Updated successfully!');
    } catch (error) {
      res.status(400).send(error);
    }
  },
```

2021-07-25 11:10 UTC, OmegonAlpharius commented on src/controllers/TeacherController.js
> +};
Удаление тоже отличается от других контроллеров

2021-07-26 17:09 UTC, nurlan212 commented on src/database/seeders/20210724164340-mock-data-teachers.js
> +};
исправлено

2021-07-26 17:09 UTC, nurlan212 commented on src/controllers/TeacherController.js
> +  },
исправлено

2021-07-26 17:10 UTC, nurlan212 commented on src/controllers/TeacherController.js
> +};
исправлено

2021-07-26 20:05 UTC, OmegonAlpharius approved these changes

2021-07-27 03:44 UTC, BauyrjanSeidahmet requested changes

2021-07-27 03:44 UTC, BauyrjanSeidahmet commented on src/controllers/TeacherController.js
> +const { deleteById } = require('./StreamController');
Удалить неиспользуемые импорты

2021-07-27 03:44 UTC, BauyrjanSeidahmet commented on src/controllers/TeacherController.js
> +        const updatedTeacher = await Teacher.update(req.body);
Функция редактирования данных не работает.
```suggestion
        const updatedTeacher = await teacher.update(req.body);
```

2021-07-27 03:44 UTC, BauyrjanSeidahmet commented on src/database/seeders/20210726151520-mock-data-users.js
> +  up: async (queryInterface, Sequelize) => {
Убрать неиспользуемый параметр
```suggestion
  up: async (queryInterface) => {
```

2021-07-27 03:44 UTC, BauyrjanSeidahmet commented on src/database/seeders/20210726151520-mock-data-users.js
> +  down: async (queryInterface, Sequelize) => {
Убрать неиспользуемый параметр
```suggestion
  down: async (queryInterface,) => {
```

2021-07-27 03:44 UTC, BauyrjanSeidahmet commented on src/database/migrations/20210724121514-create-teacher.js
> +  down: async (queryInterface, Sequelize) => {
Убрать неиспользуемый параметр
```suggestion
  down: async (queryInterface) => {
```

2021-07-27 03:57 UTC, BauyrjanSeidahmet requested changes

2021-07-27 03:57 UTC, BauyrjanSeidahmet commented on src/database/migrations/20210724121514-create-teacher.js
> +};
Нужно добавить allowNull: false к обязательным полям в файле миграции

2021-07-27 03:57 UTC, BauyrjanSeidahmet commented on src/models/teacher.js
> +};
Нужно добавить allowNull: false к обязательным полям в модели

2021-07-28 10:18 UTC, nurlan212 commented on src/controllers/TeacherController.js
> +const { deleteById } = require('./StreamController');
исправлен

2021-07-28 10:18 UTC, nurlan212 commented on src/controllers/TeacherController.js
> +        const updatedTeacher = await Teacher.update(req.body);
исправлен

2021-07-28 10:18 UTC, nurlan212 commented on src/database/seeders/20210726151520-mock-data-users.js
> +  up: async (queryInterface, Sequelize) => {
исправлен

2021-07-28 10:18 UTC, nurlan212 commented on src/database/seeders/20210726151520-mock-data-users.js
> +  down: async (queryInterface, Sequelize) => {
исправлен

2021-07-28 10:18 UTC, nurlan212 commented on src/database/migrations/20210724121514-create-teacher.js
> +  down: async (queryInterface, Sequelize) => {
исправлен

2021-07-28 10:19 UTC, nurlan212 commented on src/database/migrations/20210724121514-create-teacher.js
> +};
исправлен

2021-07-28 10:19 UTC, nurlan212 commented on src/models/teacher.js
> +};
исправлен

2021-07-29 02:54 UTC, BauyrjanSeidahmet approved these changes

2021-07-29 02:54 UTC, merged