добавлено виртуальное поле Статус оплаты в сущность Payment
xx3u/amal_backend pull request #76
Opened 2021-07-25 14:26 UTC by BauyrjanSeidahmet

#57 
Добавлено виртуальное поле Статус оплаты в сущность Payment
Дата 25.07.2021
Затраченное время: 1 час

2021-07-26 08:24 UTC, OmegonAlpharius commented on src/models/payment.js
> +      statusPayment: {
Название модели не нужно в поле добавлять,  при использовании Paymet.status лучше читаться  будет чем 
Paymet. statusPayment
```suggestion
      status: {
```

2021-07-26 08:27 UTC, OmegonAlpharius requested changes

2021-07-26 08:27 UTC, OmegonAlpharius commented on src/models/payment.js
> +          }
Для  чего это  оборачивание в функцию?

2021-07-26 09:47 UTC, BauyrjanSeidahmet commented on src/models/payment.js
> +      statusPayment: {
исправлено

2021-07-26 09:47 UTC, BauyrjanSeidahmet commented on src/models/payment.js
> +          }
исправлено

2021-07-26 14:28 UTC, OmegonAlpharius commented on src/models/payment.js
> +            dateLimit = new Date(dateCopy.getFullYear(), dateCopy.getMonth() + 2, 1);
Эта часть всегда возвращает первое число, наверно минус потерялся?
тогда будет последний день след месяца
```suggestion
            dateLimit = new Date(dateCopy.getFullYear(), dateCopy.getMonth() + 2, -1);
```

2021-07-27 02:01 UTC, BauyrjanSeidahmet commented on src/models/payment.js
> +            dateLimit = new Date(dateCopy.getFullYear(), dateCopy.getMonth() + 2, 1);
Нет, там должен быть +1, чтобы возвращался последний день след месяца.
-1 не возвращает последний день.

2021-07-27 09:16 UTC, OmegonAlpharius commented on src/helpers/helpers.js
> +    dateLimit = new Date(dateCopy.getFullYear(), dateCopy.getMonth() + 2, 1);
Этот код не возвращает последний день следующего месяца
```suggestion
    dateLimit = new Date(dateCopy.getFullYear(), dateCopy.getMonth() + 2, -1);
```

2021-07-27 10:12 UTC, OmegonAlpharius approved these changes

2021-07-27 10:25 UTC, merged