Create entity subject
xx3u/amal_backend pull request #80
Opened 2021-07-27 11:27 UTC by ZaurQoban

Номер тикета:

#62 

Создана сущность, АПИ, сиды и миграция для предметов. Пока параметр teacherId не связан с аналогичной сущностью, а представляет собой просто числовое значение. В будущем предстоит модифицировать и создать связь с учителями.

Затраченное время: Ок 2 часов (без учета исправлений, изучения методов и тестов)

2021-07-28 09:46 UTC, OmegonAlpharius requested changes

2021-07-28 09:46 UTC, OmegonAlpharius commented on package.json
> +    "joi": "^17.4.1",
В этой ветке не должно быть этой зависимости

2021-07-28 09:46 UTC, OmegonAlpharius commented on src/database/migrations/20210727095258-create-subject.js
> +      },
У предмета не должно быть этого поля
```suggestion

```

2021-07-28 09:46 UTC, OmegonAlpharius commented on src/database/seeders/20210710124704-add_students_groupId.js
> +  // eslint-disable-next-line no-unused-vars
Лучше не использовать исключения eslint, и этот файл не относиться к тикету,
проверяй какие изменения  коммитишь
```suggestion

```

2021-07-28 09:46 UTC, OmegonAlpharius commented on src/database/seeders/20210727104910-mock-data-subjects.js
> +        teacherId: 1,
Здесь не нужен teacherId
```suggestion
 
```

2021-07-28 09:46 UTC, OmegonAlpharius commented on src/database/seeders/20210727104910-mock-data-subjects.js
> +        teacherId: 2,
Здесь не нужен teacherId
```suggestion
     
```

2021-07-28 09:46 UTC, OmegonAlpharius commented on src/routes/StudentRoutes.js
>  router.put('/:id', StudentController.updateOne);
Так же изменен файл не относящийся к задачи

2021-07-28 10:20 UTC, ZaurQoban commented on src/routes/StudentRoutes.js
>  router.put('/:id', StudentController.updateOne);
@OmegonAlpharius Вернул обратно строку

2021-07-28 10:21 UTC, ZaurQoban commented on src/database/seeders/20210727104910-mock-data-subjects.js
> +        teacherId: 2,
@OmegonAlpharius Удалил

2021-07-28 10:21 UTC, ZaurQoban commented on src/database/seeders/20210727104910-mock-data-subjects.js
> +        teacherId: 1,
@OmegonAlpharius Удалил

2021-07-28 10:21 UTC, ZaurQoban commented on src/database/seeders/20210710124704-add_students_groupId.js
> +  // eslint-disable-next-line no-unused-vars
@OmegonAlpharius Убрал

2021-07-28 10:22 UTC, ZaurQoban commented on src/database/migrations/20210727095258-create-subject.js
> +      },
@OmegonAlpharius  Убрал поле

2021-07-28 10:22 UTC, ZaurQoban commented on package.json
> +    "joi": "^17.4.1",
@OmegonAlpharius  Удалено

2021-07-28 11:29 UTC, OmegonAlpharius commented on src/database/migrations/20210727095258-create-subject.js
> +        type: Sequelize.STRING,
Поле обязательное же
```suggestion
        allowNull: false,
        type: Sequelize.STRING,
```

2021-07-28 11:29 UTC, OmegonAlpharius commented on package.json
> +    "seed:undo": "sequelize-cli db:seed:undo:all"
Не должно быть изменений этого файла в этой ветке

2021-07-28 11:47 UTC, ZaurQoban commented on package.json
> +    "seed:undo": "sequelize-cli db:seed:undo:all"
@OmegonAlpharius  А о каких изменениях идет речь? Там только удаление зависимости joi было, остальное - не трогалось

2021-07-28 11:49 UTC, ZaurQoban commented on src/database/migrations/20210727095258-create-subject.js
> +        type: Sequelize.STRING,
@OmegonAlpharius  Добавил

2021-07-29 11:01 UTC, ZaurQoban commented on package.json
> +    "seed:undo": "sequelize-cli db:seed:undo:all"
@OmegonAlpharius Вернул пробел

2021-07-29 12:06 UTC, OmegonAlpharius approved these changes

2021-07-30 05:11 UTC, BauyrjanSeidahmet requested changes

2021-07-30 05:11 UTC, BauyrjanSeidahmet commented on src/models/subject.js
> +      subjectName: DataTypes.STRING,
Нужно добавить allowNull:false и unique:true в модели, так как поле обязательное и название предмета уникальное
```suggestion
      subjectName: {
        type: DataTypes.STRING,
        allowNull: false,
        unique: true,
      },
```

2021-07-30 05:11 UTC, BauyrjanSeidahmet commented on src/database/migrations/20210727095258-create-subject.js
> +        type: Sequelize.STRING,
Название предмета уникальное
```suggestion
      subjectName: {
        allowNull: false,
        unique: true,
        type: Sequelize.STRING,
```

2021-07-30 05:11 UTC, BauyrjanSeidahmet commented on src/controllers/SubjectController.js
> +  },
Функция добавления предмета работает только с третьего раза

2021-07-30 05:38 UTC, ZaurQoban commented on src/models/subject.js
> +      subjectName: DataTypes.STRING,
@BauyrjanSeidahmet Переправил

2021-07-30 05:39 UTC, ZaurQoban commented on src/database/migrations/20210727095258-create-subject.js
> +        type: Sequelize.STRING,
@BauyrjanSeidahmet Переправил

2021-07-30 05:50 UTC, BauyrjanSeidahmet requested changes

2021-07-30 05:50 UTC, BauyrjanSeidahmet commented on src/models/subject.js
> +      subjectName: DataTypes.STRING,
Правка не правильная, посмотри внимательнее на suggested code

2021-07-30 06:01 UTC, ZaurQoban commented on src/models/subject.js
> +      subjectName: DataTypes.STRING,
@BauyrjanSeidahmet  Да, проморгал этот момент. Переправил

2021-07-30 06:05 UTC, BauyrjanSeidahmet approved these changes

2021-07-30 06:05 UTC, merged